name: moneylink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  fl_chart: ^0.66.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2  # If using authentication
  cloud_firestore: ^5.6.6  # If using Firestore
  firebase_storage: ^12.4.5  # If using Storage
  firebase_messaging: ^15.2.5
  firebase_ui_auth: ^1.10.0 # If using Push Notifications
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_bg.jpg
    - assets/images/profile.jpg
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/theme.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
